### ISSUE TITLE
Skywars

### ISSUE THREAD

**Issue by PollefeysC** [KevinPriv/HypixelApi4J#4]
I can't seem to find the skywars stats in this. Am I being dumb or is it not there?

**Comment by KevinPriv** [comment]
Added in 1.7

**Comment by KevinPriv** [comment]
Added in 1.7

**Comment by PollefeysC** [comment]
Hey, I noticed that when I build your newest release it has the SW stats in the original files, but the gradle dependencies still build a jar that has 1.5 in the name and doesn't have skywars. Is this still bugged or did I wrongly build it?
